export { Footer } from './Footer'
export { GitHubCorner } from './GitHubCorner'
export { QuizBackground } from './QuizBackground'
export { QuizLogo } from './QuizLogo'
export { Widget } from './Widget'
export { ThemeSelect } from './SelectTheme'